In [1]:
import tensorflow as tf

In [3]:
tf.__version__

'2.2.0'

# Tensor

In [7]:
import numpy as np
np.array([1,2,3]).shape

(3,)

In [9]:
np.array([[1,2,3],[4,5,6]]).shape

(2, 3)

In [10]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [11]:
tf.constant(((1,2,3),(4,5,6,)))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [14]:
arr = np.array([1,2,3])
tensor = tf.constant(arr)
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

# Properties

In [15]:
arr = np.array([1,2,3])
tensor = tf.constant(arr)

In [16]:
tensor.shape

TensorShape([3])

In [17]:
tensor.dtype

tf.int32

In [18]:
tensor.numpy()

array([1, 2, 3])

In [19]:
np.array(tensor)

array([1, 2, 3])

In [20]:
arr = np.array([1,2,3], dtype=np.float32)

In [22]:
tensor = tf.constant([1,2,3], dtype= tf.float32)
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

# convert dtype

In [24]:
arr.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

In [25]:
tf.cast(tensor, tf.uint8)

<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([1, 2, 3], dtype=uint8)>

# random

In [27]:
np.random.randn(9)
# 기본적으로 정규분포를 따른다

array([ 0.1115283 ,  0.22095279, -0.89355258, -0.02801881, -2.05064484,
        0.18509638,  0.14894613, -0.88085478,  0.80496402])

In [28]:
tf.random.normal([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.59563154,  0.7980176 , -0.69242513],
       [-1.3336107 , -0.9290202 , -0.01684259],
       [ 0.42022067,  0.5951389 ,  0.09256547]], dtype=float32)>

In [29]:
tf.random.uniform([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.64199686, 0.5603138 , 0.55393517],
       [0.13128006, 0.6890075 , 0.07455254],
       [0.78766656, 0.880033  , 0.12935424]], dtype=float32)>